/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioBharatFintechRouteImport } from './routes/portfolio.bharat-fintech'
import { Route as PortfolioFinnFintechRouteImport } from './routes/portfolio.finn-fintech'
import { Route as PortfolioRuralStayIndiaRouteImport } from './routes/portfolio.rural-stay-india'
import { Route as PortfolioSageMediaRouteImport } from './routes/portfolio.sage-media'
import { Route as PortfolioSaieshaEVehiclesRouteImport } from './routes/portfolio.saiesha-e-vehicles'
import { Route as PortfolioVaibhavOxygensRouteImport } from './routes/portfolio.vaibhav-oxygens'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesArtificialIntelligenceRouteImport } from './routes/services.artificial-intelligence'
import { Route as ServicesAutomationRouteImport } from './routes/services.automation'
import { Route as ServicesCloudDevopsRouteImport } from './routes/services.cloud-devops'
import { Route as ServicesCybersecurityRouteImport } from './routes/services.cybersecurity'
import { Route as ServicesDataAnalyticsRouteImport } from './routes/services.data-analytics'
import { Route as ServicesMachineLearningRouteImport } from './routes/services.machine-learning'
import { Route as ServicesProductDevelopmentRouteImport } from './routes/services.product-development'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services.software-development'
import { Route as ServicesTechnologyConsultingRouteImport } from './routes/services.technology-consulting'
import { Route as ServicesUiUxDesignRouteImport } from './routes/services.ui-ux-design'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsAiSolutionsRouteImport } from './routes/solutions.ai-solutions'
import { Route as SolutionsAnalyticsSolutionsRouteImport } from './routes/solutions.analytics-solutions'
import { Route as SolutionsAutomationSolutionsRouteImport } from './routes/solutions.automation-solutions'
import { Route as SolutionsBusinessIntelligenceRouteImport } from './routes/solutions.business-intelligence'
import { Route as SolutionsCustomSoftwareRouteImport } from './routes/solutions.custom-software'
import { Route as SolutionsDigitalTransformationRouteImport } from './routes/solutions.digital-transformation'
import { Route as SolutionsEnterpriseSolutionsRouteImport } from './routes/solutions.enterprise-solutions'
import { Route as SolutionsSaasSolutionsRouteImport } from './routes/solutions.saas-solutions'
import { Route as SolutionsStartupSolutionsRouteImport } from './routes/solutions.startup-solutions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioBharatFintechRoute = PortfolioBharatFintechRouteImport.update({
  id: '/bharat-fintech',
  path: '/bharat-fintech',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioFinnFintechRoute = PortfolioFinnFintechRouteImport.update({
  id: '/finn-fintech',
  path: '/finn-fintech',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioRuralStayIndiaRoute = PortfolioRuralStayIndiaRouteImport.update({
  id: '/rural-stay-india',
  path: '/rural-stay-india',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioSageMediaRoute = PortfolioSageMediaRouteImport.update({
  id: '/sage-media',
  path: '/sage-media',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioSaieshaEVehiclesRoute =
  PortfolioSaieshaEVehiclesRouteImport.update({
    id: '/saiesha-e-vehicles',
    path: '/saiesha-e-vehicles',
    getParentRoute: () => PortfolioRoute,
  } as any)
const PortfolioVaibhavOxygensRoute = PortfolioVaibhavOxygensRouteImport.update({
  id: '/vaibhav-oxygens',
  path: '/vaibhav-oxygens',
  getParentRoute: () => PortfolioRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesArtificialIntelligenceRoute =
  ServicesArtificialIntelligenceRouteImport.update({
    id: '/artificial-intelligence',
    path: '/artificial-intelligence',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudDevopsRoute = ServicesCloudDevopsRouteImport.update({
  id: '/cloud-devops',
  path: '/cloud-devops',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCybersecurityRoute = ServicesCybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDataAnalyticsRoute = ServicesDataAnalyticsRouteImport.update({
  id: '/data-analytics',
  path: '/data-analytics',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMachineLearningRoute = ServicesMachineLearningRouteImport.update({
  id: '/machine-learning',
  path: '/machine-learning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesProductDevelopmentRoute =
  ServicesProductDevelopmentRouteImport.update({
    id: '/product-development',
    path: '/product-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/software-development',
    path: '/software-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesTechnologyConsultingRoute =
  ServicesTechnologyConsultingRouteImport.update({
    id: '/technology-consulting',
    path: '/technology-consulting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesUiUxDesignRoute = ServicesUiUxDesignRouteImport.update({
  id: '/ui-ux-design',
  path: '/ui-ux-design',
  getParentRoute: () => ServicesRoute,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAiSolutionsRoute = SolutionsAiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAnalyticsSolutionsRoute =
  SolutionsAnalyticsSolutionsRouteImport.update({
    id: '/analytics-solutions',
    path: '/analytics-solutions',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsAutomationSolutionsRoute =
  SolutionsAutomationSolutionsRouteImport.update({
    id: '/automation-solutions',
    path: '/automation-solutions',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsBusinessIntelligenceRoute =
  SolutionsBusinessIntelligenceRouteImport.update({
    id: '/business-intelligence',
    path: '/business-intelligence',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsCustomSoftwareRoute = SolutionsCustomSoftwareRouteImport.update({
  id: '/custom-software',
  path: '/custom-software',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsDigitalTransformationRoute =
  SolutionsDigitalTransformationRouteImport.update({
    id: '/digital-transformation',
    path: '/digital-transformation',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsEnterpriseSolutionsRoute =
  SolutionsEnterpriseSolutionsRouteImport.update({
    id: '/enterprise-solutions',
    path: '/enterprise-solutions',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsSaasSolutionsRoute = SolutionsSaasSolutionsRouteImport.update({
  id: '/saas-solutions',
  path: '/saas-solutions',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsStartupSolutionsRoute =
  SolutionsStartupSolutionsRouteImport.update({
    id: '/startup-solutions',
    path: '/startup-solutions',
    getParentRoute: () => SolutionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-a-call': typeof BookACallRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/portfolio/bharat-fintech': typeof PortfolioBharatFintechRoute
  '/portfolio/finn-fintech': typeof PortfolioFinnFintechRoute
  '/portfolio/rural-stay-india': typeof PortfolioRuralStayIndiaRoute
  '/portfolio/sage-media': typeof PortfolioSageMediaRoute
  '/portfolio/saiesha-e-vehicles': typeof PortfolioSaieshaEVehiclesRoute
  '/portfolio/vaibhav-oxygens': typeof PortfolioVaibhavOxygensRoute
  '/services/artificial-intelligence': typeof ServicesArtificialIntelligenceRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-analytics': typeof ServicesDataAnalyticsRoute
  '/services/machine-learning': typeof ServicesMachineLearningRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/technology-consulting': typeof ServicesTechnologyConsultingRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/solutions/ai-solutions': typeof SolutionsAiSolutionsRoute
  '/solutions/analytics-solutions': typeof SolutionsAnalyticsSolutionsRoute
  '/solutions/automation-solutions': typeof SolutionsAutomationSolutionsRoute
  '/solutions/business-intelligence': typeof SolutionsBusinessIntelligenceRoute
  '/solutions/custom-software': typeof SolutionsCustomSoftwareRoute
  '/solutions/digital-transformation': typeof SolutionsDigitalTransformationRoute
  '/solutions/enterprise-solutions': typeof SolutionsEnterpriseSolutionsRoute
  '/solutions/saas-solutions': typeof SolutionsSaasSolutionsRoute
  '/solutions/startup-solutions': typeof SolutionsStartupSolutionsRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-a-call': typeof BookACallRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/portfolio/bharat-fintech': typeof PortfolioBharatFintechRoute
  '/portfolio/finn-fintech': typeof PortfolioFinnFintechRoute
  '/portfolio/rural-stay-india': typeof PortfolioRuralStayIndiaRoute
  '/portfolio/sage-media': typeof PortfolioSageMediaRoute
  '/portfolio/saiesha-e-vehicles': typeof PortfolioSaieshaEVehiclesRoute
  '/portfolio/vaibhav-oxygens': typeof PortfolioVaibhavOxygensRoute
  '/services/artificial-intelligence': typeof ServicesArtificialIntelligenceRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-analytics': typeof ServicesDataAnalyticsRoute
  '/services/machine-learning': typeof ServicesMachineLearningRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/technology-consulting': typeof ServicesTechnologyConsultingRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/solutions/ai-solutions': typeof SolutionsAiSolutionsRoute
  '/solutions/analytics-solutions': typeof SolutionsAnalyticsSolutionsRoute
  '/solutions/automation-solutions': typeof SolutionsAutomationSolutionsRoute
  '/solutions/business-intelligence': typeof SolutionsBusinessIntelligenceRoute
  '/solutions/custom-software': typeof SolutionsCustomSoftwareRoute
  '/solutions/digital-transformation': typeof SolutionsDigitalTransformationRoute
  '/solutions/enterprise-solutions': typeof SolutionsEnterpriseSolutionsRoute
  '/solutions/saas-solutions': typeof SolutionsSaasSolutionsRoute
  '/solutions/startup-solutions': typeof SolutionsStartupSolutionsRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/services': typeof ServicesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-a-call': typeof BookACallRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/portfolio/bharat-fintech': typeof PortfolioBharatFintechRoute
  '/portfolio/finn-fintech': typeof PortfolioFinnFintechRoute
  '/portfolio/rural-stay-india': typeof PortfolioRuralStayIndiaRoute
  '/portfolio/sage-media': typeof PortfolioSageMediaRoute
  '/portfolio/saiesha-e-vehicles': typeof PortfolioSaieshaEVehiclesRoute
  '/portfolio/vaibhav-oxygens': typeof PortfolioVaibhavOxygensRoute
  '/services/artificial-intelligence': typeof ServicesArtificialIntelligenceRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-analytics': typeof ServicesDataAnalyticsRoute
  '/services/machine-learning': typeof ServicesMachineLearningRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/technology-consulting': typeof ServicesTechnologyConsultingRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/solutions/ai-solutions': typeof SolutionsAiSolutionsRoute
  '/solutions/analytics-solutions': typeof SolutionsAnalyticsSolutionsRoute
  '/solutions/automation-solutions': typeof SolutionsAutomationSolutionsRoute
  '/solutions/business-intelligence': typeof SolutionsBusinessIntelligenceRoute
  '/solutions/custom-software': typeof SolutionsCustomSoftwareRoute
  '/solutions/digital-transformation': typeof SolutionsDigitalTransformationRoute
  '/solutions/enterprise-solutions': typeof SolutionsEnterpriseSolutionsRoute
  '/solutions/saas-solutions': typeof SolutionsSaasSolutionsRoute
  '/solutions/startup-solutions': typeof SolutionsStartupSolutionsRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-a-call'
    | '/contact'
    | '/industries'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/solutions'
    | '/portfolio/bharat-fintech'
    | '/portfolio/finn-fintech'
    | '/portfolio/rural-stay-india'
    | '/portfolio/sage-media'
    | '/portfolio/saiesha-e-vehicles'
    | '/portfolio/vaibhav-oxygens'
    | '/services/artificial-intelligence'
    | '/services/automation'
    | '/services/cloud-devops'
    | '/services/cybersecurity'
    | '/services/data-analytics'
    | '/services/machine-learning'
    | '/services/product-development'
    | '/services/software-development'
    | '/services/technology-consulting'
    | '/services/ui-ux-design'
    | '/solutions/ai-solutions'
    | '/solutions/analytics-solutions'
    | '/solutions/automation-solutions'
    | '/solutions/business-intelligence'
    | '/solutions/custom-software'
    | '/solutions/digital-transformation'
    | '/solutions/enterprise-solutions'
    | '/solutions/saas-solutions'
    | '/solutions/startup-solutions'
    | '/portfolio/'
    | '/services/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-a-call'
    | '/contact'
    | '/industries'
    | '/pricing'
    | '/portfolio/bharat-fintech'
    | '/portfolio/finn-fintech'
    | '/portfolio/rural-stay-india'
    | '/portfolio/sage-media'
    | '/portfolio/saiesha-e-vehicles'
    | '/portfolio/vaibhav-oxygens'
    | '/services/artificial-intelligence'
    | '/services/automation'
    | '/services/cloud-devops'
    | '/services/cybersecurity'
    | '/services/data-analytics'
    | '/services/machine-learning'
    | '/services/product-development'
    | '/services/software-development'
    | '/services/technology-consulting'
    | '/services/ui-ux-design'
    | '/solutions/ai-solutions'
    | '/solutions/analytics-solutions'
    | '/solutions/automation-solutions'
    | '/solutions/business-intelligence'
    | '/solutions/custom-software'
    | '/solutions/digital-transformation'
    | '/solutions/enterprise-solutions'
    | '/solutions/saas-solutions'
    | '/solutions/startup-solutions'
    | '/portfolio'
    | '/services'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-a-call'
    | '/contact'
    | '/industries'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/solutions'
    | '/portfolio/bharat-fintech'
    | '/portfolio/finn-fintech'
    | '/portfolio/rural-stay-india'
    | '/portfolio/sage-media'
    | '/portfolio/saiesha-e-vehicles'
    | '/portfolio/vaibhav-oxygens'
    | '/services/artificial-intelligence'
    | '/services/automation'
    | '/services/cloud-devops'
    | '/services/cybersecurity'
    | '/services/data-analytics'
    | '/services/machine-learning'
    | '/services/product-development'
    | '/services/software-development'
    | '/services/technology-consulting'
    | '/services/ui-ux-design'
    | '/solutions/ai-solutions'
    | '/solutions/analytics-solutions'
    | '/solutions/automation-solutions'
    | '/solutions/business-intelligence'
    | '/solutions/custom-software'
    | '/solutions/digital-transformation'
    | '/solutions/enterprise-solutions'
    | '/solutions/saas-solutions'
    | '/solutions/startup-solutions'
    | '/portfolio/'
    | '/services/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookACallRoute: typeof BookACallRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/bharat-fintech': {
      id: '/portfolio/bharat-fintech'
      path: '/bharat-fintech'
      fullPath: '/portfolio/bharat-fintech'
      preLoaderRoute: typeof PortfolioBharatFintechRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/finn-fintech': {
      id: '/portfolio/finn-fintech'
      path: '/finn-fintech'
      fullPath: '/portfolio/finn-fintech'
      preLoaderRoute: typeof PortfolioFinnFintechRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/rural-stay-india': {
      id: '/portfolio/rural-stay-india'
      path: '/rural-stay-india'
      fullPath: '/portfolio/rural-stay-india'
      preLoaderRoute: typeof PortfolioRuralStayIndiaRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/sage-media': {
      id: '/portfolio/sage-media'
      path: '/sage-media'
      fullPath: '/portfolio/sage-media'
      preLoaderRoute: typeof PortfolioSageMediaRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/saiesha-e-vehicles': {
      id: '/portfolio/saiesha-e-vehicles'
      path: '/saiesha-e-vehicles'
      fullPath: '/portfolio/saiesha-e-vehicles'
      preLoaderRoute: typeof PortfolioSaieshaEVehiclesRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/vaibhav-oxygens': {
      id: '/portfolio/vaibhav-oxygens'
      path: '/vaibhav-oxygens'
      fullPath: '/portfolio/vaibhav-oxygens'
      preLoaderRoute: typeof PortfolioVaibhavOxygensRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/artificial-intelligence': {
      id: '/services/artificial-intelligence'
      path: '/artificial-intelligence'
      fullPath: '/services/artificial-intelligence'
      preLoaderRoute: typeof ServicesArtificialIntelligenceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-devops': {
      id: '/services/cloud-devops'
      path: '/cloud-devops'
      fullPath: '/services/cloud-devops'
      preLoaderRoute: typeof ServicesCloudDevopsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cybersecurity': {
      id: '/services/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/services/cybersecurity'
      preLoaderRoute: typeof ServicesCybersecurityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/data-analytics': {
      id: '/services/data-analytics'
      path: '/data-analytics'
      fullPath: '/services/data-analytics'
      preLoaderRoute: typeof ServicesDataAnalyticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/machine-learning': {
      id: '/services/machine-learning'
      path: '/machine-learning'
      fullPath: '/services/machine-learning'
      preLoaderRoute: typeof ServicesMachineLearningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/product-development': {
      id: '/services/product-development'
      path: '/product-development'
      fullPath: '/services/product-development'
      preLoaderRoute: typeof ServicesProductDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/technology-consulting': {
      id: '/services/technology-consulting'
      path: '/technology-consulting'
      fullPath: '/services/technology-consulting'
      preLoaderRoute: typeof ServicesTechnologyConsultingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ui-ux-design': {
      id: '/services/ui-ux-design'
      path: '/ui-ux-design'
      fullPath: '/services/ui-ux-design'
      preLoaderRoute: typeof ServicesUiUxDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/ai-solutions': {
      id: '/solutions/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/solutions/ai-solutions'
      preLoaderRoute: typeof SolutionsAiSolutionsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/analytics-solutions': {
      id: '/solutions/analytics-solutions'
      path: '/analytics-solutions'
      fullPath: '/solutions/analytics-solutions'
      preLoaderRoute: typeof SolutionsAnalyticsSolutionsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/automation-solutions': {
      id: '/solutions/automation-solutions'
      path: '/automation-solutions'
      fullPath: '/solutions/automation-solutions'
      preLoaderRoute: typeof SolutionsAutomationSolutionsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/business-intelligence': {
      id: '/solutions/business-intelligence'
      path: '/business-intelligence'
      fullPath: '/solutions/business-intelligence'
      preLoaderRoute: typeof SolutionsBusinessIntelligenceRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/custom-software': {
      id: '/solutions/custom-software'
      path: '/custom-software'
      fullPath: '/solutions/custom-software'
      preLoaderRoute: typeof SolutionsCustomSoftwareRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/digital-transformation': {
      id: '/solutions/digital-transformation'
      path: '/digital-transformation'
      fullPath: '/solutions/digital-transformation'
      preLoaderRoute: typeof SolutionsDigitalTransformationRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/enterprise-solutions': {
      id: '/solutions/enterprise-solutions'
      path: '/enterprise-solutions'
      fullPath: '/solutions/enterprise-solutions'
      preLoaderRoute: typeof SolutionsEnterpriseSolutionsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/saas-solutions': {
      id: '/solutions/saas-solutions'
      path: '/saas-solutions'
      fullPath: '/solutions/saas-solutions'
      preLoaderRoute: typeof SolutionsSaasSolutionsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/startup-solutions': {
      id: '/solutions/startup-solutions'
      path: '/startup-solutions'
      fullPath: '/solutions/startup-solutions'
      preLoaderRoute: typeof SolutionsStartupSolutionsRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioBharatFintechRoute: typeof PortfolioBharatFintechRoute
  PortfolioFinnFintechRoute: typeof PortfolioFinnFintechRoute
  PortfolioRuralStayIndiaRoute: typeof PortfolioRuralStayIndiaRoute
  PortfolioSageMediaRoute: typeof PortfolioSageMediaRoute
  PortfolioSaieshaEVehiclesRoute: typeof PortfolioSaieshaEVehiclesRoute
  PortfolioVaibhavOxygensRoute: typeof PortfolioVaibhavOxygensRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioBharatFintechRoute: PortfolioBharatFintechRoute,
  PortfolioFinnFintechRoute: PortfolioFinnFintechRoute,
  PortfolioRuralStayIndiaRoute: PortfolioRuralStayIndiaRoute,
  PortfolioSageMediaRoute: PortfolioSageMediaRoute,
  PortfolioSaieshaEVehiclesRoute: PortfolioSaieshaEVehiclesRoute,
  PortfolioVaibhavOxygensRoute: PortfolioVaibhavOxygensRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ServicesRouteChildren {
  ServicesArtificialIntelligenceRoute: typeof ServicesArtificialIntelligenceRoute
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesCloudDevopsRoute: typeof ServicesCloudDevopsRoute
  ServicesCybersecurityRoute: typeof ServicesCybersecurityRoute
  ServicesDataAnalyticsRoute: typeof ServicesDataAnalyticsRoute
  ServicesMachineLearningRoute: typeof ServicesMachineLearningRoute
  ServicesProductDevelopmentRoute: typeof ServicesProductDevelopmentRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
  ServicesTechnologyConsultingRoute: typeof ServicesTechnologyConsultingRoute
  ServicesUiUxDesignRoute: typeof ServicesUiUxDesignRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesArtificialIntelligenceRoute: ServicesArtificialIntelligenceRoute,
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesCloudDevopsRoute: ServicesCloudDevopsRoute,
  ServicesCybersecurityRoute: ServicesCybersecurityRoute,
  ServicesDataAnalyticsRoute: ServicesDataAnalyticsRoute,
  ServicesMachineLearningRoute: ServicesMachineLearningRoute,
  ServicesProductDevelopmentRoute: ServicesProductDevelopmentRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
  ServicesTechnologyConsultingRoute: ServicesTechnologyConsultingRoute,
  ServicesUiUxDesignRoute: ServicesUiUxDesignRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsAiSolutionsRoute: typeof SolutionsAiSolutionsRoute
  SolutionsAnalyticsSolutionsRoute: typeof SolutionsAnalyticsSolutionsRoute
  SolutionsAutomationSolutionsRoute: typeof SolutionsAutomationSolutionsRoute
  SolutionsBusinessIntelligenceRoute: typeof SolutionsBusinessIntelligenceRoute
  SolutionsCustomSoftwareRoute: typeof SolutionsCustomSoftwareRoute
  SolutionsDigitalTransformationRoute: typeof SolutionsDigitalTransformationRoute
  SolutionsEnterpriseSolutionsRoute: typeof SolutionsEnterpriseSolutionsRoute
  SolutionsSaasSolutionsRoute: typeof SolutionsSaasSolutionsRoute
  SolutionsStartupSolutionsRoute: typeof SolutionsStartupSolutionsRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAiSolutionsRoute: SolutionsAiSolutionsRoute,
  SolutionsAnalyticsSolutionsRoute: SolutionsAnalyticsSolutionsRoute,
  SolutionsAutomationSolutionsRoute: SolutionsAutomationSolutionsRoute,
  SolutionsBusinessIntelligenceRoute: SolutionsBusinessIntelligenceRoute,
  SolutionsCustomSoftwareRoute: SolutionsCustomSoftwareRoute,
  SolutionsDigitalTransformationRoute: SolutionsDigitalTransformationRoute,
  SolutionsEnterpriseSolutionsRoute: SolutionsEnterpriseSolutionsRoute,
  SolutionsSaasSolutionsRoute: SolutionsSaasSolutionsRoute,
  SolutionsStartupSolutionsRoute: SolutionsStartupSolutionsRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookACallRoute: BookACallRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
